docs_dir: docs
site_name: Robotický tábor 2023
site_url: https://2023.robotickytabor.cz/
site_description: >-
  Robotický tábor 2023

repo_name: RoboticsBrno/RoboCamp-2023
repo_url: https://github.com/RoboticsBrno/RoboCamp-2023
# edit_uri: blob/main/docs/

# Copyright
copyright: Copyright © 2023 RoboticsBrno
use_directory_urls: True

theme:
  name: material
  language: cs
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

  # custom_dir: overrides

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-sunny
        name: Přepnout na světý režim
    - scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-night
        name: Přepnout na tmavý režim


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - attr_list
  - pymdownx.tabbed
  - pymdownx.snippets:
      url_download: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
    - open-in-new-tab
    - glightbox


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_robotarna_
#   analytics:
#     provider: google
#     property: ASD

extra_javascript:
  - assets/config.js


nav:
    - Domů:
        - index.md